# Generated by Django 2.2.4 on 2019-09-07 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=128, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=128)),
                ('lname', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.EmailField(max_length=128)),
                ('type', models.CharField(choices=[('D', 'Dog'), ('C', 'Cat')], max_length=1)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petadoption.User')),
            ],
        ),
    ]
