# Generated by Django 2.2.4 on 2019-10-11 18:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('petadoption', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
