# Generated by Django 2.2.4 on 2019-10-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petadoption', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_profile_image',
            field=models.ImageField(upload_to='D:\\projects\\petfinder\\media\\pet_profile_image'),
        ),
    ]
