# Generated by Django 2.2.4 on 2019-10-11 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petadoption', '0002_auto_20191009_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('message_no', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('message', models.CharField(default='message', max_length=128)),
                ('message_writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='up_for_adoption',
            new_name='Up_for_Adoption',
        ),
        migrations.AddField(
            model_name='adoption_requests',
            name='requester_username',
            field=models.ForeignKey(default='Your Usename', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='adoption_requests',
            name='request_description',
            field=models.TextField(default='Message', max_length=500),
        ),
        migrations.AlterField(
            model_name='adoption_requests',
            name='requester_email',
            field=models.EmailField(default='Your email', max_length=128),
        ),
        migrations.AlterField(
            model_name='adoption_requests',
            name='requester_phone_no',
            field=models.CharField(default='Your phone no', max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='animal_type',
            field=models.CharField(choices=[('D', 'Dog'), ('C', 'Cat')], default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='pet',
            name='description',
            field=models.TextField(default='description', max_length=128),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_profile_image',
            field=models.ImageField(upload_to='D:\\projects\\petadoption\\media\\pet_profile_image'),
        ),
        migrations.AlterField(
            model_name='pet_photos',
            name='photo_id',
            field=models.ForeignKey(default='petid', on_delete=django.db.models.deletion.CASCADE, to='petadoption.Pet'),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
