# Generated by Django 2.2.4 on 2019-09-27 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petadoption', '0002_auto_20190907_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='type',
            new_name='animal_type',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='id',
            new_name='pet_id',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='image',
            new_name='pet_profile_image',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='name',
        ),
        migrations.AddField(
            model_name='pet',
            name='Up_for_Adoption',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_name',
            field=models.CharField(default='Pets name', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='pass', max_length=128),
        ),
        migrations.AlterField(
            model_name='pet',
            name='description',
            field=models.TextField(max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='fname',
            field=models.CharField(default='fname', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='lname',
            field=models.CharField(default='lname', max_length=128),
        ),
        migrations.CreateModel(
            name='Pet_Photos',
            fields=[
                ('photo_no', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('pet_image', models.ImageField(upload_to='')),
                ('photo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petadoption.Pet')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_no', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('comment', models.CharField(default='Comment', max_length=128)),
                ('comment_writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petadoption.User')),
                ('picture_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petadoption.Pet_Photos')),
            ],
        ),
        migrations.CreateModel(
            name='Adoption_requests',
            fields=[
                ('request_no', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('requester_name', models.CharField(default='Your name', max_length=128)),
                ('requester_phone_no', models.CharField(default='Yor phone no', max_length=10)),
                ('request_description', models.TextField(max_length=500)),
                ('requester_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petadoption.User')),
            ],
        ),
    ]
