# Generated by Django 2.2.4 on 2019-10-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petadoption', '0002_pet_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_profile_image',
            field=models.ImageField(upload_to='D:\\projects\\petadoption\\media\\pet_profile_image'),
        ),
    ]
