# Generated by Django 2.2.4 on 2019-10-11 16:24

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('petadoption', '0003_auto_20190927_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=128)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('message_no', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('message', models.CharField(default='message', max_length=128)),
                ('message_writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='adoption_requests',
            name='request_description',
            field=models.TextField(default='Message', max_length=500),
        ),
        migrations.AlterField(
            model_name='adoption_requests',
            name='requester_email',
            field=models.EmailField(default='Your email', max_length=128),
        ),
        migrations.AlterField(
            model_name='adoption_requests',
            name='requester_phone_no',
            field=models.CharField(default='Your phone no', max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='animal_type',
            field=models.CharField(choices=[('D', 'Dog'), ('C', 'Cat')], default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='pet',
            name='description',
            field=models.TextField(default='description', max_length=128),
        ),
        migrations.AlterField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_profile_image',
            field=models.ImageField(upload_to='D:\\projects\\petadoption\\media\\pet_profile_image'),
        ),
        migrations.AlterField(
            model_name='pet_photos',
            name='photo_id',
            field=models.ForeignKey(default='petid', on_delete=django.db.models.deletion.CASCADE, to='petadoption.Pet'),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='adoption_requests',
            name='requester_username',
            field=models.ForeignKey(default='Your username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
