# Generated by Django 2.2.4 on 2019-10-21 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petadoption', '0003_auto_20191020_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adoption_requests',
            old_name='request_description',
            new_name='description_message',
        ),
        migrations.RenameField(
            model_name='adoption_requests',
            old_name='requester_username',
            new_name='requester',
        ),
        migrations.RemoveField(
            model_name='adoption_requests',
            name='requester_email',
        ),
        migrations.RemoveField(
            model_name='adoption_requests',
            name='requester_name',
        ),
        migrations.RemoveField(
            model_name='adoption_requests',
            name='requester_phone_no',
        ),
        migrations.AddField(
            model_name='adoption_requests',
            name='pet',
            field=models.ForeignKey(default="Pet's name", on_delete=django.db.models.deletion.CASCADE, to='petadoption.Pet'),
        ),
        migrations.AddField(
            model_name='adoption_requests',
            name='phone_no',
            field=models.CharField(default='Phone Number', max_length=10),
        ),
        migrations.AddField(
            model_name='myuser',
            name='address',
            field=models.TextField(default='address', max_length=1024),
        ),
        migrations.AddField(
            model_name='pet',
            name='age',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='pet',
            name='breed',
            field=models.CharField(default='breed', max_length=128),
        ),
        migrations.AddField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='adoption_requests',
            name='request_no',
            field=models.AutoField(max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.CharField(max_length=1024),
        ),
    ]
