# Generated by Django 2.2.4 on 2019-10-21 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petadoption', '0004_auto_20191021_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption_requests',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petadoption.Pet'),
        ),
    ]
