# Generated by Django 2.2.4 on 2019-10-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petadoption', '0005_auto_20191021_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_name',
            field=models.CharField(max_length=128),
        ),
    ]
